#!/usr/bin/env python3
"""
rebrand.py - Rebrand a Trane equipment submittal to KCC.

Driven by CONTENT (search), not page/coordinate hardcoding, so it works across
the whole family of Trane submittals generated by the same submittal software,
regardless of page count or where the logo/model cell lands.

What it does:
  1. Replaces every "Trane" text token with "KCC" (footers, "U.S. Inc.",
     "<X> is pleased...", "Trane Equipment Submittal", etc.) using true
     redaction, so the original word is removed from the file - not just hidden.
  2. Replaces the product-line brand ("Horizon" -> "KCC") on word boundaries,
     so "Horizontal Return" is never touched. Keeps the original (TM) glyph and
     aligns the new word to it so it reads "KCC(TM)".
  3. Detects the header logo (small image, top-left) on every page and swaps it
     for the KCC logo, fitted without stretching.

Usage:
  python rebrand.py input.pdf                 -> input_KCC.pdf
  python rebrand.py input.pdf output.pdf
  python rebrand.py input.pdf --logo kcc.png  -> use a different logo file
"""
import os, re, sys, argparse
import fitz  # PyMuPDF

TM = "\u2122"

DEFAULT_CONFIG = {
    # literal substring replacements applied to every text span
    "text_replacements": [("Trane", "KCC")],
    # whole-word brand replacements (regex word boundaries -> protects "Horizontal")
    "brand_replacements": {"Horizon": "KCC"},
    # any span containing one of these is left completely untouched (extra safety)
    "protect_substrings": [],
    # header-logo detection envelope (PDF points; origin top-left)
    "logo": {
        "header_max_y0": 130, "left_max_x0": 235,
        "min_w": 60, "max_w": 260, "min_h": 25, "max_h": 95,
        "min_aspect": 1.5, "max_aspect": 5.0,
    },
}


def _apply_replacements(text, cfg):
    out = text
    for a, b in cfg["text_replacements"]:
        out = out.replace(a, b)
    for brand, tgt in cfg["brand_replacements"].items():
        out = re.sub(r"\b" + re.escape(brand) + r"\b", tgt, out)
    return out


def _alias(font):
    return "hebo" if "bold" in font.lower() else "helv"


def _split_tail(old, new, cfg):
    """If a replaced token sits at the END of the span (so a (TM) span follows it),
    return (head, tail) so we can right-align the tail against the (TM)."""
    for brand, tgt in cfg["brand_replacements"].items():
        if old.rstrip().endswith(brand) and new.endswith(tgt):
            return new[: len(new) - len(tgt)], tgt
    for a, b in cfg["text_replacements"]:
        if old.rstrip().endswith(a) and new.endswith(b):
            return new[: len(new) - len(b)], b
    return None, None


def rebrand_pdf(in_path, out_path, logo_path, config=None):
    cfg = {**DEFAULT_CONFIG, **(config or {})}
    cfg["logo"] = {**DEFAULT_CONFIG["logo"], **(cfg.get("logo") or {})}
    report = {"text": [], "logos": [], "warnings": []}

    doc = fitz.open(in_path)

    # ---------- collect text jobs (capture span data BEFORE redacting) ----------
    text_jobs = []
    page_span_rects = {pno: [] for pno in range(len(doc))}
    for pno in range(len(doc)):
        for blk in doc[pno].get_text("dict")["blocks"]:
            for line in blk.get("lines", []):
                spans = line["spans"]
                for s in spans:
                    if s["text"].strip():
                        page_span_rects[pno].append(fitz.Rect(s["bbox"]))
                for i, s in enumerate(spans):
                    txt = s["text"]
                    if any(p in txt for p in cfg["protect_substrings"]):
                        continue
                    new = _apply_replacements(txt, cfg)
                    if new == txt:
                        continue
                    tm_next = (i + 1 < len(spans)
                               and spans[i + 1]["text"].lstrip().startswith(TM))
                    text_jobs.append({
                        "pno": pno, "bbox": fitz.Rect(s["bbox"]),
                        "origin": s["origin"], "size": s["size"],
                        "alias": _alias(s["font"]), "old": txt, "new": new,
                        "tm_next": tm_next,
                    })

    # ---------- collect logo jobs ----------
    L = cfg["logo"]
    logo_jobs = []
    for pno in range(len(doc)):
        page = doc[pno]
        for img in page.get_images(full=True):
            xref = img[0]
            for r in page.get_image_rects(xref):
                w, h = r.width, r.height
                if h <= 0:
                    continue
                ar = w / h
                if (r.y0 < L["header_max_y0"] and r.x0 < L["left_max_x0"]
                        and L["min_w"] <= w <= L["max_w"]
                        and L["min_h"] <= h <= L["max_h"]
                        and L["min_aspect"] <= ar <= L["max_aspect"]):
                    logo_jobs.append((pno, xref, r))

    # ---------- pass 1: redact the text we will rewrite ----------
    # Redact a glyph-band around the baseline, then clamp it so it stops just
    # short of any other text line directly above/below (handles cramped,
    # word-wrapped cells without eating neighbouring lines' characters).
    for j in text_jobs:
        oy, sz, b = j["origin"][1], j["size"], j["bbox"]
        ry0, ry1 = oy - 0.85 * sz, oy + 0.30 * sz
        for o in page_span_rects[j["pno"]]:
            if abs(o.y0 - b.y0) < 0.5 and abs(o.x0 - b.x0) < 0.5:
                continue                       # the span itself
            if o.x1 <= b.x0 or o.x0 >= b.x1:
                continue                       # no horizontal overlap
            if o.y0 >= oy:                      # a line below this one
                ry1 = min(ry1, o.y0 - 0.1)
            elif o.y1 <= oy:                    # a line above this one
                ry0 = max(ry0, o.y1 + 0.1)
        if ry1 <= ry0:                          # degenerate -> fall back tight
            ry0, ry1 = oy - 0.7 * sz, oy + 0.05 * sz
        doc[j["pno"]].add_redact_annot(
            fitz.Rect(b.x0 - 0.3, ry0, b.x1 + 0.3, ry1), fill=(1, 1, 1))
    for page in doc:
        page.apply_redactions(images=fitz.PDF_REDACT_IMAGE_NONE,
                              graphics=fitz.PDF_REDACT_LINE_ART_NONE,
                              text=fitz.PDF_REDACT_TEXT_REMOVE)

    # ---------- pass 2: write replacement text ----------
    fonts = {"helv": fitz.Font("helv"), "hebo": fitz.Font("hebo")}
    for j in text_jobs:
        page, f, size = doc[j["pno"]], fonts[j["alias"]], j["size"]
        y = j["origin"][1]
        if j["tm_next"]:
            head, tail = _split_tail(j["old"], j["new"], cfg)
            x1 = j["bbox"].x1
            if tail is not None:
                page.insert_text((x1 - f.text_length(tail, size), y), tail,
                                 fontname=j["alias"], fontsize=size, color=(0, 0, 0))
                if head:
                    page.insert_text((j["origin"][0], y), head,
                                     fontname=j["alias"], fontsize=size, color=(0, 0, 0))
            else:  # fallback: right-align whole string to the (TM)
                page.insert_text((x1 - f.text_length(j["new"], size), y), j["new"],
                                 fontname=j["alias"], fontsize=size, color=(0, 0, 0))
        else:
            page.insert_text(j["origin"], j["new"],
                             fontname=j["alias"], fontsize=size, color=(0, 0, 0))
        report["text"].append((j["pno"] + 1, j["old"], j["new"]))

    # ---------- pass 3: swap logos ----------
    if logo_jobs:
        if not os.path.exists(logo_path):
            report["warnings"].append(f"Logo file not found: {logo_path} - logos NOT replaced.")
        else:
            with fitz.open(logo_path) as limg:
                kw, kh = limg[0].rect.width, limg[0].rect.height
            ar = kh / kw
            deleted = set()
            for pno, xref, rect in logo_jobs:
                page = doc[pno]
                if xref not in deleted:
                    page.delete_image(xref)
                    deleted.add(xref)
                w = rect.width
                place = fitz.Rect(rect.x0, rect.y0, rect.x0 + w, rect.y0 + w * ar)
                page.insert_image(place, filename=logo_path,
                                  keep_proportion=True, overlay=True)
                report["logos"].append((pno + 1, tuple(round(v, 1) for v in rect)))
    else:
        report["warnings"].append("No header logo detected - check the logo envelope in CONFIG.")

    # ---------- residual-brand audit ----------
    full = "".join(p.get_text() for p in doc)
    for brand in ["Trane"] + list(cfg["brand_replacements"].keys()):
        n = len(re.findall(r"\b" + re.escape(brand) + r"\b", full))
        if n:
            report["warnings"].append(f"{n} residual '{brand}' token(s) remain - review.")

    doc.save(out_path, garbage=4, deflate=True, clean=True)
    doc.close()
    return report


def _cli():
    ap = argparse.ArgumentParser(description="Rebrand a Trane submittal to KCC.")
    ap.add_argument("input")
    ap.add_argument("output", nargs="?")
    ap.add_argument("--logo", default=os.path.join(os.path.dirname(__file__), "kcc_logo.png"))
    a = ap.parse_args()
    out = a.output or re.sub(r"\.pdf$", "_KCC.pdf", a.input, flags=re.I)
    rep = rebrand_pdf(a.input, out, a.logo)
    print(f"Wrote {out}")
    print(f"  text replacements: {len(rep['text'])}")
    print(f"  logos swapped:     {len(rep['logos'])} on page(s) {[p for p,_ in rep['logos']]}")
    for w in rep["warnings"]:
        print(f"  WARNING: {w}")


if __name__ == "__main__":
    _cli()
